### ISSUE TITLE
Add option to supply :match and :skip paramaters

### ISSUE THREAD

**Issue by flurin** [DigitPaint/roger_scsslint#6]
So we can specify which files we want to be tested; the behaviour should be the same as with release processors (they use this function: https://github.com/DigitPaint/roger/blob/master/lib/roger/release.rb#L195)

**Comment by hkrutzer** [comment]
These can be defined in the `.scss-lint.yml` (which would be used by standalone scss-lint). I think it's undesirable to have two locations for configuring the same thing.

**Comment by flurin** [comment]
I agree. But it feels kind of weird that all other linters/processors/etc. in Roger have these options but this linter does not.

We keep it like this for now and see ;)
